export class Hotel {
  constructor(public id:string, public name:string, public description:string, public address:string, public phone:string,
              public firstAvatarUrl:string, public secondAvatarUrl:string, public largeAvatarUrl:string,
              public hotelType:string) {
  }
}

const imageUrl = 'app/components/hotels/hotel/images';

export const HotelMocks:Array<Hotel> = [
  new Hotel(
    '0',
    'DoubleTree by Hilton',
    'Bright rooms & suites in an elegant hotel featuring a bar, 2 restaurants & a gym with a sauna.',
    'Kerkstraat 25, 1017 GA Amsterdam',
    '020 561 3636',
    `${imageUrl}/1.jpg`,
    `${imageUrl}/2.jpg`,
    `${imageUrl}/big-1.jpg`,
    'HOSTEL'),
  new Hotel(
    '1',
    'Lloyd Hotel',
    'Contemporary rooms in an eclectic hotel with a restaurant/bar & a free ferry to Centraal Station.',
    'Pieter Cornelisz Hooftstraat 2, 1071 BX Amsterdam',
    '020 710 6000',
    `${imageUrl}/3.jpg`,
    `${imageUrl}/4.jpg`,
    `${imageUrl}/big-2.jpg`,
    'HOTEL'),
  new Hotel(
    '2',
    'Hotel De Hallen',
    'Chic rooms in a polished hotel overlooking a canal, plus a trendy bar & free breakfast.',
    'Spaarndammerdijk 302, 1013 ZX Amsterdam',
    '020 530 6200',
    `${imageUrl}/5.jpg`,
    `${imageUrl}/6.jpg`,
    `${imageUrl}/big-3.jpg`,
    'APARTMENT'),
  new Hotel(
    '3',
    'Downtown Hotel',
    'Trendy rooms & suites in 2 historic buildings, plus a spa, an opulent restaurant & a rooftop bar.',
    'Oostelijke Handelskade 34, 1019 BN Amsterdam',
    '020 530 6200',
    `${imageUrl}/7.jpg`,
    `${imageUrl}/8.jpg`,
    `${imageUrl}/big-4.jpg`,
    'HOTEL'),
  new Hotel(
    '4',
    'Uptown Hotel',
    'Suites in 2 historic buildings, plus a spa, an opulent restaurant & a rooftop bar.',
    'Oostelijke Handelskade 34, 1019 BN Amsterdam',
    '020 530 6200',
    `${imageUrl}/9.jpg`,
    `${imageUrl}/1.jpg`,
    `${imageUrl}/big-5.jpg`,
    'HOSTEL'),
  new Hotel(
    '5',
    'Easy Hotel',
    'Suites in 2 historic buildings, plus a spa, an opulent restaurant & a rooftop bar.',
    'Hoofdstraat 23, 1126 BN Amsterdam',
    '020 530 6200',
    `${imageUrl}/2.jpg`,
    `${imageUrl}/3.jpg`,
    `${imageUrl}/big-6.jpg`,
    'HOTEL'),
  new Hotel(
    '6',
    'Hilton Hotel',
    'Suites in 2 historic buildings, plus a spa, an opulent restaurant & a rooftop bar.',
    'Hoofdstraat 77, 1146 BN Amsterdam',
    '020 530 6200',
    `${imageUrl}/4.jpg`,
    `${imageUrl}/5.jpg`,
    `${imageUrl}/big-7.jpg`,
    'HOSTEL'),
  new Hotel(
    '7',
    'Apartment Hotel',
    'Suites in 2 historic buildings, plus a spa, an opulent restaurant & a rooftop bar.',
    'Hoofdstraat 77, 1146 BN Amsterdam',
    '020 530 6200',
    `${imageUrl}/6.jpg`,
    `${imageUrl}/7.jpg`,
    `${imageUrl}/big-8.jpg`,
    'APARTMENT')];
